server:
  port: 9999

spring:
  application:
    name: authorization-server
  cloud:
    nacos:
      discovery:
        server-addr: time-server:8848
  datasource:
    url: jdbc:mysql://time-server:3307/time-manage?useSSL=false&serverTimezon=GMT%28
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: sky378797
    hikari:
      connection-timeout: 60000
      validation-timeout: 3000
      idle-timeout: 60000
      login-timeout: 5
      max-lifetime: 60000
      maximum-pool-size: 10
      minimum-idle: 10
      read-only: false